### ISSUE TITLE
Some way to make sound effects through blender.

### ISSUE THREAD

**Issue by brokenps2** [ABelliqueux/blender_io_export_psx_mesh#4]
I think it would be good for the engine to use blender's sound features to add some sound to it.

**Comment by ABelliqueux** [comment]
Sound is not implemented in the engine yet but will hopefully be at some point. 

Can you be more specific about what you mean by blender's sound features ? Do you mean the logic editor's sound actuator ?

![2021-07-27-110750_335x154_scrot](https://user-images.githubusercontent.com/1405255/127127998-91d29209-3742-4757-9209-6298986609f2.png)

**Comment by elithom09** [comment]
Yes, I do.

**Comment by ABelliqueux** [comment]
Ok, so after looking a bit into it, logic is not accessible from the python console, so I think the best way to have sound is to use the `speaker` object, that has nice parameters and has a location and orientation. 

![2021-08-10-163443_782x411_scrot](https://user-images.githubusercontent.com/1405255/128886644-bb29c253-992e-46ea-a617-6280376a2363.png)

**Comment by ABelliqueux** [comment]
- [x] Add sound loading to engine 
- [x] Add sound playback code to engine https://github.com/ABelliqueux/3dcam-headers/commit/17d30079cadea835cdca4a82193914e05f8413a8
- [x] Add sound conversion to blender script (ffmpeg+psxavenc) https://github.com/ABelliqueux/blender_io_export_psx_mesh/commit/b5df633d48c83ea862f3320156c2ce793542bcb6
  - [x] Generate individual VAG files
  - [x] Generate individual XA files
  - [x] Generate XA mux file for use with `xainterleave`
  - [x] Generate interlaced XA file
  - [x] Add sound objects to levels
- [x] Add 3d sound capabilities to engine https://github.com/ABelliqueux/3dcam-headers/commit/4bc75f43a5fa26ada63eb931d01b55f5afa94e87

**Comment by ABelliqueux** [comment]
Done.
